### ISSUE TITLE
cityscapes的阈值

### ISSUE THREAD

**Issue by zdk258** [BBBBchan/CorrMatch#12]
感谢出彩的工作！在论文中说到
> And same to UniMatch [61], we set the confidence threshold τ to 0 for the Cityscapes dataset.

意思是cityscapes数据集不使用动态阈值而是固定为0吗？
是因为动态阈值在cityscapes数据集效果不好吗？

**Comment by BBBBchan** [comment]
您好，感谢您的关注。
是的，与UniMatch一致，我们在Cityscapes数据集中将阈值固定为0，没有使用动态阈值。
事实上，固定阈值和动态阈值在Cityscapes数据集上的表现都稍逊于固定阈值为0。我们的猜想是，Cityscapes数据集中场景较为复杂，小目标更多，全局阈值策略不能很好的建模每个目标的置信度，进而导致高置信度区域受限。

**Comment by zdk258** [comment]
感谢回复
