### ISSUE TITLE
相关映射的意义

### ISSUE THREAD

**Issue by Dzrb** [BBBBchan/CorrMatch#13]
您好，请问为什么特征向量自己和自己生成的相关性图可以凸显形状信息啊？我有点不明白

**Comment by BBBBchan** [comment]
您好，感谢您的关注！
首先，之前的很多工作已经证明，骨干网络(Backbone)中提取到的深层次特征能够编码抽象语义信息；其次，特征自己和自己生成的相关性图的每一行都可以被视为某一位置的特征向量对全部位置特征向量的相似程度。
因此，当我们取骨干网络的深层特征来计算自己和自己的相关性图时，每一行都可以表示当前位置的特征和全图所有位置特征的在语义上的相似程度。进一步来说，两个位置的特征向量对应的语义信息越接近，其在相关性图上的相似程度就越高。所以，在我们建立的相关性图的每一行上，与当前位置语义相近的位置的相关性会相对较高，因此每一行都可以在语义层面建模出类别无关的形状信息。

**Comment by Dzrb** [comment]
感谢您的回复！
