### ISSUE TITLE
请问如何可视化推理所得的掩码图像？

### ISSUE THREAD

**Issue by hindinbush** [BBBBchan/CorrMatch#15]
您好，非常感谢您出色的工作，请问在训练结束之后，如何获得预测所得的掩码图像？

**Comment by BBBBchan** [comment]
您好，感谢您的关注。
我们已经上传了掩码图像可视化的代码。 您可以在`vis_mask.py`中修改checkpoint和保存路径信息，并运行`sh tools/vis_mask.sh <gpu num> <port>`进行可视化。

**Comment by hindinbush** [comment]
> 您好，感谢您的关注。 我们已经上传了掩码图像可视化的代码。 您可以在`vis_mask.py`中修改checkpoint和保存路径信息，并运行`sh tools/vis_mask.sh <gpu num> <port>`进行可视化。

非常感谢您的回复，这对我帮助很大，后续有什么不懂得地方我可能还得再麻烦您解答一下哈哈，感谢！
