### ISSUE TITLE
模型测试

### ISSUE THREAD

**Issue by LoveOverOrStart** [BBBBchan/CorrMatch#20]
你好，能否提供一下在pascal voc上训练的weight，感谢

**Comment by BBBBchan** [comment]
Hi there. We have uploaded trained checkpoints on the Pascal VOC 2012 standard splits with 321 crop size. You can download and  use them with this [Google Drive](https://drive.google.com/drive/folders/11y-WqgFn6tSrh8XzPkFlyrRh0dEXRvR6?usp=drive_link).

**Comment by LoveOverOrStart** [comment]
> Hi there. We have uploaded trained checkpoints on the Pascal VOC 2012 standard splits with 321 crop size. You can download and use them with this [Google Drive](https://drive.google.com/drive/folders/11y-WqgFn6tSrh8XzPkFlyrRh0dEXRvR6?usp=drive_link).

Thank you
