### ISSUE TITLE
Backward Issue

### ISSUE THREAD

**Issue by facias914** [BBBBchan/CorrMatch#24]
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by BBBBchan** [comment]
It seems like an error caused by an in-place operation, such as the `inplace` parameter in ReLU. Could you provide more details about your code setup or any modifications you have made?

**Comment by lixinbo6666** [comment]
I met the same question : 
![Y7H27KVKJ31_0NGP3U9%L7D](https://github.com/user-attachments/assets/1d150cac-bc6d-400b-afaa-bffee918b8c7)

**Comment by BBBBchan** [comment]
Hi there. As mentioned above, it looks like this issue is related with in-place operation on tensors. Maybe it is caused by ReLU or nn.Dropout2d(). 
However, I haven't met this problem during experiments and couldn't reproduce your problem with my environment. Thus, could you please share more information?
1. Your change to the code if you have any.
2. Your environment information, especially pytorch version.

**Comment by lixinbo6666** [comment]
> Hi there. As mentioned above, it looks like this issue is related with in-place operation on tensors. Maybe it is caused by ReLU or nn.Dropout2d(). However, I haven't met this problem during experiments and couldn't reproduce your problem with my environment. Thus, could you please share more information?
> 
> 1. Your change to the code if you have any.
> 2. Your environment information, especially pytorch version.

Hello, I didn't modify any code. I just followed the MD documentation to set up the environment and run it. I'm running on a single 4090 GPU, and the dependency versions are as follows:
![UL)CL44TVXEE 9Z%OFSDQ~B](https://github.com/user-attachments/assets/20dbc320-5641-44d8-88fa-8703b6ae93c3)

**Comment by BBBBchan** [comment]
That would be a bit strange. Did you follow the configuration and launch scripts provided in our README? Since you use a single 4090, it should be `sh tools/train.sh 1 <port>`

**Comment by BBBBchan** [comment]
Hi there. I might find out about this problem. In line 32 of `corrmatch.py`, we set the system-visible GPU numbers to 0,1, which is suitable for training with two GPUs.  You could try changing this line to: `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.

**Comment by lixinbo6666** [comment]
> Hi there. I might find out about this problem. In line 32 of `corrmatch.py`, we set the system-visible GPU numbers to 0,1, which is suitable for training with two GPUs. You could try changing this line to: `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.

Hello, I made the changes but still got the same error. However, I think it might be a problem with the GPU. I'll try running it on both GPUs tomorrow to see if that solves the issue.

**Comment by BBBBchan** [comment]
> > Hi there. I might find out about this problem. In line 32 of `corrmatch.py`, we set the system-visible GPU numbers to 0,1, which is suitable for training with two GPUs. You could try changing this line to: `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.
> 
> Hello, I made the changes but still got the same error. However, I think it might be a problem with the GPU. I'll try running it on both GPUs tomorrow to see if that solves the issue.

Alright. Looking forward to your progress and response.

**Comment by lixinbo6666** [comment]
> > > Hi there. I might find out about this problem. In line 32 of `corrmatch.py`, we set the system-visible GPU numbers to 0,1, which is suitable for training with two GPUs. You could try changing this line to: `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.
> > 
> > 
> > Hello, I made the changes but still got the same error. However, I think it might be a problem with the GPU. I'll try running it on both GPUs tomorrow to see if that solves the issue.
> 
> Alright. Looking forward to your progress and response.

Hello, I have solved the problem. The root cause of the issue was that I needed to train with multiple GPUs. I can now train with two GPUs at the same time. If I only use a single GPU, I will get the same error again. Thank you for your patience in helping me.

**Comment by BBBBchan** [comment]
> > > > Hi there. I might find out about this problem. In line 32 of `corrmatch.py`, we set the system-visible GPU numbers to 0,1, which is suitable for training with two GPUs. You could try changing this line to: `os.environ["CUDA_VISIBLE_DEVICES"] = "0"`.
> > > 
> > > 
> > > Hello, I made the changes but still got the same error. However, I think it might be a problem with the GPU. I'll try running it on both GPUs tomorrow to see if that solves the issue.
> > 
> > 
> > Alright. Looking forward to your progress and response.
> 
> Hello, I have solved the problem. The root cause of the issue was that I needed to train with multiple GPUs. I can now train with two GPUs at the same time. If I only use a single GPU, I will get the same error again. Thank you for your patience in helping me.

Glad to hear that! We will further investigate the issue of being unable to train with a single GPU and will let you know if we can fix that.

**Comment by Hotcat-s** [comment]
I had the same problem when I used a single GPU!!!   I don’t know if this problem can be solved

**Comment by Xiadonn** [comment]
I have encountered the same error...😅

**Comment by Xiadonn** [comment]
I have solved this problem by specifying `broadcast_buffers=False` for `torch.nn.parallel.DistributedDataParallel`. I found this solution [here](https://blog.csdn.net/qq_39237205/article/details/125728708).
