### ISSUE TITLE
nclass error

### ISSUE THREAD

**Issue by cj534-art** [BBBBchan/CorrMatch#25]
Hello, author. If my data has already annotated the background, and let's say I have 4 categories in total, how can I solve the problem when setting nclass to 4 causes an error?

**Comment by BBBBchan** [comment]
Hello, thank you for your attention. Theoretically speaking, if you wish to train on a custom dataset, in addition to modifying the dataset section (and `ignore_index`  if needed) in the configuration file (`config/xx.yaml`), you also need to split the dataset according to whether it is labeled or not (you can refer to the file format under the `partitions` directory). Moreover, if you are using a different form of data format (for example, if the label files of some datasets require a conversion from RGB to P), you may also need to modify the data reading and processing parts in `dataset/semi.py` as necessary.

**Comment by cj534-art** [comment]
Thank you for your reply. However, I still have some doubts about the ignore_index. I hope you can help clarify why it is often set to 255 instead of 0 when we want to ignore the background.

**Comment by BBBBchan** [comment]
Hi there. 

It should be clarified that 255 is not the background class label. In fact, using Pascal as an example, the class labeled as 0 is the background class. The `ignore_index` 255 indicates pixels that should be ignored during training and evaluation. These pixels often appear at the edges of objects or as padding introduced by data augmentation. In fact, both in loss computation and evaluation, the background class with label 0 is included in the calculations.

If you want to ignore the background class by setting `ignore_index` to 0, you might need to ensure that the class labeled as 0 does not participate in the computations. Another possible solution is to process the label images when reading them, mapping the 0 class to 255.

**Comment by cj534-art** [comment]
thank you ,I know，

**Comment by cj534-art** [comment]
I apologize for disturbing you repeatedly, but it's because I'm very interested in your article and would like to try it on my own dataset. My label file contains six classes (including the background), with pixel values of 1, 2, 3, 4, 5, and 6 (similar to the Potsdam data format). Therefore, I don't have a label with pixel value 0. When I set nclass to six classes, I always encounter errors. I suspect that it might be because 0-pixel labels are automatically added when reading the labels, but after reading the code, I didn't find any such functionality. So I'm not clear about how the labels are read. so,I hope you can provide some advice.

**Comment by BBBBchan** [comment]
Thank you for your attention. First, since there are six categories in your dataset, the `nclass` should be set to 6. The error you're encountering is because the model's predicted results, after passing through `argmax`, range from [0, 5]. Therefore, when calculating the loss and evaluating against a category labeled as 6, an out-of-bounds error occurs. In my view, the most direct way to tackle this issue is to subtract 1 when reading the labels, changing them from 1-6 to 0-5.
