### ISSUE TITLE
The final model files

### ISSUE THREAD

**Issue by Hugo-cell111** [BBBBchan/CorrMatch#7]
Hi! Could you release the well-trained ckpt model files that can reproduce the experimental results in the paper? Thanks!

**Comment by BBBBchan** [comment]
Hi there. We have uploaded trained checkpoints on the Pascal VOC 2012 standard splits with 321 crop size. You can download and  use them with this [Google Drive](https://drive.google.com/drive/folders/11y-WqgFn6tSrh8XzPkFlyrRh0dEXRvR6?usp=drive_link).

**Comment by Hugo-cell111** [comment]
Thanks!
