### ISSUE TITLE
Question about the Per-pixel thresholding in the appendix

### ISSUE THREAD

**Issue by Hugo-cell111** [BBBBchan/CorrMatch#8]
Hi! Could you explain what's the meaning of per-pixel threshold? I can't fully get the meaning. Thanks!

**Comment by BBBBchan** [comment]
Hi there, sorry for the confusion. 
The per-pixel thresholding strategy mentioned in Appendix E.1 is a trivial approach. This strategy assigns independent thresholds to each pixel position and updates them individually, which is conceptually equivalent to treating each pixel location as an independent classification task.
This experiment aims to illustrate that it is inappropriate to simply treat the segmentation task as an independent per-pixel classification task, so it is inappropriate to directly use the common threshold strategies in semi-supervised classification tasks.
